// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc8hJSNfSHRhummEzSaG8Cg7xrgFGprQI',
    appId: '1:1006179038785:web:cdef68de4e79a5d2e1f8c0',
    messagingSenderId: '1006179038785',
    projectId: 'machine-test-quadleo',
    authDomain: 'machine-test-quadleo.firebaseapp.com',
    storageBucket: 'machine-test-quadleo.firebasestorage.app',
    measurementId: 'G-ZQGQX938JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN1IFKHhLfebLvDDf4Aem-MEr1mIl1DBA',
    appId: '1:1006179038785:android:390a976bfaa5ae4fe1f8c0',
    messagingSenderId: '1006179038785',
    projectId: 'machine-test-quadleo',
    storageBucket: 'machine-test-quadleo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_kpcb8qgjD8zYQfnJILtrkOZ235QTx_o',
    appId: '1:1006179038785:ios:c67c91e2eb74437ae1f8c0',
    messagingSenderId: '1006179038785',
    projectId: 'machine-test-quadleo',
    storageBucket: 'machine-test-quadleo.firebasestorage.app',
    iosBundleId: 'com.example.machineTestQuadleo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_kpcb8qgjD8zYQfnJILtrkOZ235QTx_o',
    appId: '1:1006179038785:ios:c67c91e2eb74437ae1f8c0',
    messagingSenderId: '1006179038785',
    projectId: 'machine-test-quadleo',
    storageBucket: 'machine-test-quadleo.firebasestorage.app',
    iosBundleId: 'com.example.machineTestQuadleo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc8hJSNfSHRhummEzSaG8Cg7xrgFGprQI',
    appId: '1:1006179038785:web:c8bf014ed310d319e1f8c0',
    messagingSenderId: '1006179038785',
    projectId: 'machine-test-quadleo',
    authDomain: 'machine-test-quadleo.firebaseapp.com',
    storageBucket: 'machine-test-quadleo.firebasestorage.app',
    measurementId: 'G-MSBNMM3SM9',
  );
}
